contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
staticdir = "static"
builddrafts = false
# baseurl = "http://www.mirellavanteulingen.nl/"
baseurl = "http://localhost:1313/"
languageCode = "en-us"
title = "Mirella van Teulingen"
canonifyurls = true

[blackfriday]
    plainIdAnchors = true

[params]
    page_name = "page_name"
    css = "css"
    twitter = "twitter"
    video = "video"
    speaker = "speaker"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Blog"
    identifier = "blog"
    url = "/blog/"
    weight = 2
[[menu.main]]
    name = "Fronteers"
    identifier = "fronteers"
    url = "/fronteers/"
    weight = 3
[[menu.main]]
    name = "About me"
    url = "/about/"
    weight = 4
